### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KeepSOBP** [KeepSOBP/Hikari#24]
```
(node:1350) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channel' of undefined

    at Object.run (/hikari/commands/music/leave.js:32:29)

    at Client.<anonymous> (/hikari/index.js:115:17)

    at Client.emit (events.js:315:20)

    at Object.PacketHandlers.MESSAGE_CREATE (/hikari/node_modules/discord.js-light/handlers.js:186:9)

    at WebSocketManager.client.ws.handlePacket (/hikari/node_modules/discord.js-light/actions.js:38:28)

    at WebSocketShard.onPacket (/hikari/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)

    at WebSocketShard.onMessage (/hikari/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)

    at WebSocket.onMessage (/hikari/node_modules/ws/lib/event-target.js:132:16)

    at WebSocket.emit (events.js:315:20)

    at Receiver.receiverOnMessage (/hikari/node_modules/ws/lib/websocket.js:825:20)

(node:1350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
```

```
(node:1350) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setSelfDeaf' of undefined

    at DisTube.<anonymous> (/hikari/index.js:135:32)

    at DisTube.emit (events.js:315:20)

    at DisTube._handleSongFinish (/hikari/node_modules/distube/src/DisTube.js:944:41)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:1350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**Comment by KeepSOBP** [comment]
maybe fixed selfdeaf error
https://github.com/KeepSOBP/Hikari/commit/8a964499e18c2f3215e9f6de9a8e47b5d81d0c4d

**Comment by KeepSOBP** [comment]
> maybe fixed selfdeaf error
> [8a96449](https://github.com/KeepSOBP/Hikari/commit/8a964499e18c2f3215e9f6de9a8e47b5d81d0c4d)

No u 😃
